/**
 * Server-only loaders for the enrichment data that lives in static JSON files
 * (same pattern as lib/geoData.ts). These carry REAL data joined per
 * neighborhood — CBS-census demographics, Police safety, and the authoritative
 * MoE schools list — and need no DB migration.
 *
 * Generated by:
 *   npm run ingest:demographics   → public/neighborhoods.demographics.json
 *   npm run ingest:crime          → public/neighborhoods.crime.json
 *   npm run ingest:schools:moe    → public/schools.modiin.json
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

function readJson<T>(file: string): T {
  return JSON.parse(readFileSync(join(process.cwd(), "public", file), "utf8")) as T;
}

/** Per-neighborhood demographics from CBS Census 2022. `null` = no coverage. */
export type Demographics = {
  population: number;
  households: number;
  household_size: number | null;
  median_age: number | null;
  pct_age_0_19: number | null;
  pct_households_with_kids_0_5: number | null;
  avg_children_born: number | null;
  pct_academic: number | null;
  median_wage_annual: number | null;
  pct_own: number | null;
  religiosity: string | null;
};

/** Per-neighborhood safety from Police 2024 data. `null` = no coverage. */
export type Safety = {
  cases_2024_total: number;
  per_1000_residents: number | null;
  safety_score: number | null;
  safety_rank: number | null;
  safety_rank_of: number;
};

export type StaticSchool = {
  semel: number;
  name_he: string;
  level: string;
  grade_from: number | null;
  grade_to: number | null;
  sector: string | null;
  supervision: string | null;
  students: number | null;
  offers_bagrut: boolean;
  lon: number | null;
  lat: number | null;
  meitzav_score: number | null;
  meitzav_year: number | null;
};

export function loadDemographics(): Record<string, Demographics | null> {
  return readJson<{ neighborhoods: Record<string, Demographics | null> }>("neighborhoods.demographics.json").neighborhoods;
}

export function loadSafety(): Record<string, Safety | null> {
  return readJson<{ neighborhoods: Record<string, Safety | null> }>("neighborhoods.crime.json").neighborhoods;
}

export function loadModiinSchools(): StaticSchool[] {
  return readJson<{ schools: StaticSchool[] }>("schools.modiin.json").schools.filter((s) => s.lon != null && s.lat != null);
}
